### ISSUE TITLE
Sysbot base not working with new update

### ISSUE THREAD

**Issue by link2026** [olliz0r/sys-botbase#37] opened 2021-04-11 19:29 UTC
The sysbot base is no longer working with atmosphere update and new switch update

**Comment by ToxicMushroom** [comment] 2021-04-12 21:30
duplicate of https://github.com/olliz0r/sys-botbase/issues/36

**Comment by link2026** [comment] 2021-04-12 22:47
Yes sorry I didn’t read his my apologies

**Closed** 2021-04-19 16:25 UTC
